version: '3.9'

services:
  postgresdb:
    container_name: postgres
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=${PGUSERNAME}
      - POSTGRES_PASSWORD=${PGPASSWORD}
      - POSTGRES_DB=${PGDATABASE} 
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports:
     - 5432:5432

  trackerapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: node:14-alpine
    container_name: nodejs
    restart: always
    ports:
      - 8080:8080
    env_file: .env
    depends_on:
      - postgresdb